spring.application.name=bloodmatch

spring.data.mongodb.uri=mongodb+srv://gabrielsilveiradeazevedo:bmpassword@1stcluster.qp0zltg.mongodb.net/bloodmatch?appName=1stCluster
spring.data.mongodb.database=bloodmatch
